<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Brand;

class RealProjectSeeder extends Seeder
{
    public function run()
    {
        $realProjects = [
            [
                'name' => 'AngieArt',
                'description' => 'Professional art portfolio website',
                'short_description' => 'Art portfolio',
                'screenshot' => '/favicons/angieart.uk.png',
                'logo' => '/favicons/angieart.uk.png',
                'website_url' => 'https://angieart.uk',
                'industry' => 'Art & Creative',
                'featured' => true,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-01-15',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'Binday',
                'description' => 'Waste management platform',
                'short_description' => 'Waste management',
                'screenshot' => '/favicons/binday.help.png',
                'logo' => '/favicons/binday.help.png',
                'website_url' => 'https://binday.help',
                'industry' => 'Environmental',
                'featured' => true,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-09-10',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'FindMyFuel',
                'description' => 'Fuel finder platform',
                'short_description' => 'Fuel finder',
                'screenshot' => '/favicons/findmyfuel.help.ico',
                'logo' => '/favicons/findmyfuel.help.ico',
                'website_url' => 'https://findmyfuel.help',
                'industry' => 'Fuel Services',
                'featured' => true,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-10-15',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'Reviewable',
                'description' => 'Review platform',
                'short_description' => 'Reviews',
                'screenshot' => '/favicons/reviewable.info.ico',
                'logo' => '/favicons/reviewable.info.ico',
                'website_url' => 'https://reviewable.info',
                'industry' => 'Reviews',
                'featured' => true,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-08-15',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'ClawAndOrder',
                'description' => 'Pet grooming booking platform',
                'short_description' => 'Pet grooming',
                'screenshot' => '/favicons/clawandorder.uk.png',
                'logo' => '/favicons/clawandorder.uk.png',
                'website_url' => 'https://clawandorder.uk',
                'industry' => 'Pet Services',
                'featured' => false,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-02-20',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'GentlePaw',
                'description' => 'Veterinary care platform',
                'short_description' => 'Veterinary care',
                'screenshot' => '/favicons/gentlepaw.uk.png',
                'logo' => '/favicons/gentlepaw.uk.png',
                'website_url' => 'https://gentlepaw.uk',
                'industry' => 'Veterinary',
                'featured' => false,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-03-10',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'Groomly',
                'description' => 'Pet grooming marketplace',
                'short_description' => 'Pet marketplace',
                'screenshot' => '/favicons/groomly.uk.png',
                'logo' => '/favicons/groomly.uk.png',
                'website_url' => 'https://groomly.uk',
                'industry' => 'Pet Services',
                'featured' => false,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-04-05',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'GuineaGuru',
                'description' => 'Guinea pig care platform',
                'short_description' => 'Pet care',
                'screenshot' => '/favicons/guineaguru.com.png',
                'logo' => '/favicons/guineaguru.com.png',
                'website_url' => 'https://guineaguru.com',
                'industry' => 'Pet Care',
                'featured' => false,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-05-12',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'HappyHoppers',
                'description' => 'Rabbit care platform',
                'short_description' => 'Rabbit care',
                'screenshot' => '/favicons/happyhoppers.info.png',
                'logo' => '/favicons/happyhoppers.info.png',
                'website_url' => 'https://happyhoppers.info',
                'industry' => 'Pet Care',
                'featured' => false,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-06-18',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'HealthyWellbeing',
                'description' => 'Wellness platform',
                'short_description' => 'Wellness',
                'screenshot' => '/favicons/healthywellbeing.info.png',
                'logo' => '/favicons/healthywellbeing.info.png',
                'website_url' => 'https://healthywellbeing.info',
                'industry' => 'Health & Wellness',
                'featured' => false,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-07-22',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'Cleaners',
                'description' => 'Cleaning services platform',
                'short_description' => 'Cleaning services',
                'screenshot' => '/favicons/cleaners.help.png',
                'logo' => '/favicons/cleaners.help.png',
                'website_url' => 'https://cleaners.help',
                'industry' => 'Cleaning Services',
                'featured' => false,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-10-01',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'PasteShare',
                'description' => 'Code sharing platform',
                'short_description' => 'Code sharing',
                'screenshot' => '/favicons/pasteshare.uk.png',
                'logo' => '/favicons/pasteshare.uk.png',
                'website_url' => 'https://pasteshare.uk',
                'industry' => 'Developer Tools',
                'featured' => false,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-11-01',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ],
            [
                'name' => 'QuantumShare',
                'description' => 'Quantum computing platform',
                'short_description' => 'Quantum computing',
                'screenshot' => '/favicons/quantumshare.co.uk.ico',
                'logo' => '/favicons/quantumshare.co.uk.ico',
                'website_url' => 'https://quantumshare.co.uk',
                'industry' => 'Quantum Computing',
                'featured' => false,
                'metrics' => [],
                'testimonial' => '',
                'testimonial_author' => '',
                'testimonial_position' => '',
                'launch_date' => '2024-11-15',
                'technologies' => [],
                'challenges' => '',
                'solutions' => '',
                'results' => ''
            ]
        ];

        // Clear existing brands and add real projects
        Brand::truncate();
        
        foreach ($realProjects as $projectData) {
            Brand::create($projectData);
        }
    }
}